OP-432 | Parametric JUnit Tests and Read generalData.properties from resources folders  (#240)
* Read generalData.properties from resources folders

     -  Update GeneralData logic to read from resources folder(s) testing
        and regular contexts:
	- Add /core/src/main/resources/generalData.properties
	- Add /core/src/test/resources/generalData.properties

     -  Add Expeimental code section in GeneralData.java for debugging:
     	- main method
	- isJUnitTest method
	- printAllProperties method

     -  Add Test org.isf.generaldata.GeneralDataTest [Disable WIP]:
     	- Conflicting to org.isf.medicalstock.test.Tests, bringing back that
	  known error that block test execution:

	  javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	  Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation:

Signed-off-by: Emerson Castaneda <emecas@users.noreply.github.com>
Co-authored-by: dbmalkovsky <david@malkovsky.org>
Co-authored-by: Alessandro Domanico <alessandro.domanico@yahoo.it>